// Forty shots. 7.5 seconds = 16 beats = four bars at 128 BPM.
// [visual, Chinese keyword, English keyword, Chinese subtitle, English subtitle]
module.exports=[
['genesis','万象未明','BEFORE ORDER','世界，充满尚未解开的可能。','The world is filled with possibilities waiting to be unlocked.'],
['vortex','一念，启程','AN IDEA IN MOTION','算法，把一个想法变成可以执行的步骤。','An algorithm turns an idea into executable steps.'],
['title','无形之舞','THE INVISIBLE CHOREOGRAPHY','看不见的规则，编排看得见的世界。','Invisible rules choreograph the visible world.'],
['lattice','从规则，到奇迹','RULES BECOME WORLDS','简单的规则，也能孕育复杂而壮丽的结果。','Simple rules can give rise to intricate, magnificent results.'],
['sort','让混沌，拥有方向','ORDER FROM CHAOS','排序，让散落的信息拥有可比较的次序。','Sorting gives scattered information a comparable order.'],
['sort','比较 · 分割','COMPARE. DIVIDE.','归并排序，先把问题逐层拆小。','Merge sort first divides the problem into smaller parts.'],
['sort','重组，成为秩序','MERGE INTO ORDER','再合并有序片段，让局部秩序汇成整体。','It merges sorted runs until local order becomes global order.'],
['sort','增长，也可以克制','O(n log n)','标准归并排序的时间复杂度为 O(n log n)。','Standard merge sort runs in O(n log n) time.'],
['binary','不必遍历，所有可能','ELIMINATE HALF','在有序数据中，二分查找每次排除约一半候选。','In sorted data, binary search eliminates about half the candidates.'],
['binary','一次判断，一次聚焦','FOCUS THE SEARCH','比较中点，让搜索范围不断收缩。','Compare the midpoint. Narrow the search interval.'],
['binary','抵达，藏在选择之后','O(log n)','随机访问有序数组时，查找只需 O(log n) 次比较。','In a sorted random-access array, search takes O(log n) comparisons.'],
['path','在城市中，寻找答案','THE SHORTEST WAY','图，把道路和连接转化为可计算的关系。','A graph turns roads and connections into computable relationships.'],
['path','让距离，一层层显形','DIJKSTRA','边权非负时，Dijkstra 逐步确定最短距离。','With nonnegative edge weights, Dijkstra settles shortest distances.'],
['path','抵达，并非偶然','A PATH IS A PROOF','每一条最短路径，都来自比较与更新。','Every shortest path emerges from comparison and relaxation.'],
['fractal','在局部，看见整体','RECURSION','递归，让问题用更小的同类问题来描述。','Recursion describes a problem through smaller instances of itself.'],
['fractal','一分为二，生生不息','SELF-SIMILARITY','一次分支，一次重复，尺度中诞生新的风景。','A branch. A repetition. New landscapes emerge across scales.'],
['fractal','边界，赋予无限以形','THE BASE CASE','终止条件，让递归最终回到可解的起点。','A base case gives recursion a place to stop and resolve.'],
['fractal','由深处，层层归来','UNWIND','子问题的答案，沿调用层次逐层返回。','Answers return through the layers of recursive calls.'],
['dp','记住，已经走过的路','DYNAMIC PROGRAMMING','动态规划，把重复的子问题变成可以复用的答案。','Dynamic programming turns repeated subproblems into reusable answers.'],
['dp','让计算，不再重来','REUSE THE ANSWER','状态记录过去，转移连接下一步。','States record what is known. Transitions connect what comes next.'],
['dp','局部的答案，汇成全局','BUILD FROM SUBPROBLEMS','在合适的状态和转移下，逐步构建整体解。','With suitable states and transitions, build the full solution step by step.'],
['dp','以空间，换取时间','A DELIBERATE TRADE','存储结果节省重复计算，也带来空间成本。','Storing results avoids repeated work, at the cost of memory.'],
['fft','拆开，一束复杂的光','FREQUENCY REVEALED','复杂信号，可以分解为不同频率的成分。','A complex signal can be decomposed into frequency components.'],
['fft','蝴蝶，穿过计算','THE BUTTERFLY','FFT 利用结构与对称，加速离散傅里叶变换。','The FFT exploits structure and symmetry to accelerate the DFT.'],
['fft','听见，隐藏的层次','FROM WAVE TO SPECTRUM','时域中的叠加，在频域中显露层次。','Superposition in time reveals its components in frequency.'],
['fft','让庞大，变得可行','O(n log n)','常见 FFT 将变换计算降至 O(n log n)。','Common FFT algorithms compute the transform in O(n log n).'],
['terrain','在起伏中，寻找更好','OPTIMIZATION','优化，为每一次选择定义一个目标。','Optimization gives each choice an objective.'],
['terrain','沿着变化，迈出一步','FOLLOW THE GRADIENT','梯度下降，沿局部最陡下降方向更新。','Gradient descent updates along the direction of steepest local decrease.'],
['terrain','更低，不一定是最低','LOCAL IS NOT GLOBAL','非凸问题中，局部最优未必是全局最优。','For nonconvex problems, a local optimum need not be global.'],
['terrain','耐心，亦是算法的一部分','ITERATE. CONVERGE.','步长、初始化与停止条件，共同影响结果。','Step size, initialization, and stopping criteria shape the result.'],
['complexity','快，意味着什么？','BEYOND THE STOPWATCH','复杂度描述规模增长时，计算成本如何变化。','Complexity describes how computational cost grows with input size.'],
['duality','时间与空间，彼此交换','TIME × SPACE','更快，可能需要更多内存；更省，也可能更慢。','Speed may require more memory. Saving memory may cost time.'],
['network','把规则，交给真实世界','FROM THEORY TO REALITY','硬件、数据分布和约束，让理论遇见现实。','Hardware, data distributions, and constraints bring theory into practice.'],
['network','漂亮，更要正确','CORRECTNESS FIRST','边界情况、正确性与验证，是优雅的根基。','Edge cases, correctness, and validation are the foundation of elegance.'],
['braid','分解 · 连接 · 重组','ONE LANGUAGE. MANY WORLDS.','排序、搜索、递归、优化，共享思考的语言。','Sorting, search, recursion, and optimization share a language of thought.'],
['braid','让秩序，流动起来','THINK IN MOTION','算法之美，在于用清晰的步骤驾驭复杂。','The beauty of algorithms lies in navigating complexity with clear steps.'],
['galaxy','从一个问题，走向宇宙','A UNIVERSE OF POSSIBILITY','从一条路径，到万千连接。','From a single path to a universe of connections.'],
['galaxy','让每一步，都有意义','EVERY STEP MATTERS','真正的力量，来自理解为什么这样前进。','Real power comes from understanding why each step works.'],
['finale','以思想，改变世界','IDEAS INTO POSSIBILITY','理解算法，让思想拥有改变世界的形状。','Understand algorithms. Give ideas the power to shape the world.'],
['finale','无形之舞','THE INVISIBLE CHOREOGRAPHY','算法之美，始于思考，成于创造。','The beauty of algorithms begins in thought and comes alive in creation.']
];
